# Expected Exception

Diese Funktionalität ist in JUnit 4 über eine Rule und Annotation abgebildet.

JUnit 5 bietet hier mehr Kontrolle über den Ablauf eines solchen Tests. assertThrows() bietet die Möglichkeit genau eine Funktion auf das Werfen einer bestimmten Exception zu überprüfen. Desweiteren wird die geworfene Exception zurückgeliefert und kann noch genauer Untersucht werden.